export const matchPasswordError = "Password is mischmasch";
export const newPasswordEqualsPasswordError = "The new password is equals the actual password";
export const newPasswordError = "The new password is mischmasch with the confirmation password";
export const internalError = "Internal error";
export const userNotFoundError = "User not found";
export const aditionalUserNotFoundError = "Aditional user not found";
export const userExistsError = "Dni number already exists";
export const mailExistsError = "Mail already exists";
export const phoneExistsError = "Phone number already exists";
export const userIdRequered = "userId is required.";
export const passwordRequered = "password is required.";
export const diaryNotFoundError = "Diary not found";
export const diaryExistsError = "Diary already exists";
export const eventNotFoundError = "Event not found";
export const eventFoundError = "Event already exists";
export const idRequered = "Id is required.";
export const reviewNotFoundError = "Review not found";
export const idsRequered = "The id carer user and the id familiar user are required";
export const allFieldRequered = "All fields are required. Missing fields: ";
export const classificationGraterThan0 = "The classifications must be more or greater than 0";
export const classificationGraterThan5 = "The classifications must be less than 5";
export const familiarNotHaveReviews = "The family member has not made any reviews";
export const reviewNotMistmach = "The review does not belong to the familiar";
export const serviceNotFoundError = "Service not found";
export const mailNotFound = "Mail not found"
export const relationNotExist = "The relation not exist"
export const invalidSpeciality = "invalid specialty."
